### PR TITLE
Add Lineage configuration.

### PR DESCRIPTION
**Pull request by felddy**
# 

## 🗣 Description

Add Lineage configuration to enable automatic PRs from upstream. 

:eyes: Please verify that the correct upstream repo was selected.

### CODE REVIEW

**Comment by jsf9k** [comment]
I will look at fixing the builds.

**Comment by jsf9k** [comment]
I had to manually merge in the latest upstream to get the GItHub Actions to pass.

**Review by mcdonnnj — APPROVED** [review]
This does some things, I like the stuff.

**Review by jsf9k — APPROVED** [review]
Great job merging in the upstream changes, @jsf9k!

**Review by dav3r — APPROVED** [review]
LGTM! 🥽

**Pull request merged**
